# on every push to the main branch, but not when there are changes to files in the .github folder.
# on every pull request with main as the base branch
# Every sunday at 6:15 UTC
# Manually

name: GitHub Actions Demo
on:
  push:
    branches: [ main ]
    paths-ignore: [.github/88]
  pull_request:
      branches: [ main]
  schedule:
      - cron: "0 2 * * 1-5"
  workflow_dispatch:
