name: GitHub Actions Demo
## for every push, pull or schedule or click of manual run,  it runs the job build
##	• on every push to the main branch, but not when there are changes to files in the .github folder.
##	• on every pull request with main as the base branch
##	• Every sunday at 6:15 UTC
## Manually
on:
  push:
    branches: [ main ]
    paths-ignore: [.github/88]
  pull_request:
      branches: [ main]
  schedule:
      - cron: '0 2 * * 1-5'
  workflow_dispatch:
jobs:
  Build:
     runs-on: ubuntu-latest
     steps:
        - run: |
            echo "🎉 The job was triggered by event: ${{ github.event_name }}"
            echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."
          
        - uses: actions/checkout@v3.0.2
  
        - name: List files in the repository
          run: |
            echo "The repository ${{ github.repository }} contains the following files:"
            tree
       
