name: GitHub Actions Demo
on:
  push:
    branches: [ main ]
    paths-ignore: [.github/88]
  pull_request:
      branches: [ main]
  schedule:
      - cron: "0 2 * * 1-5"
  workflow_dispatch:

  jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-latest
